### ISSUE TITLE
Configuring wildcards in URLs.

### ISSUE THREAD

**Issue by sbsud** [sethcottle/tabcloser#10]
I am trying to configure a url pattern that looks like `http://localhost:XXXX/<RANDOM_TEXT>` . The RANDOM_TEXT is different everytime. I am trying `^http://localhost:XXXX/.*` , but that does not seem to work. Is this pattern possible to configure?  Am I missing something?

**Comment by sethcottle** [comment]
Hi @sbsud! Right now custom URLs in TabCloser are explicit and it does not support wildcard functionality like this. I can add this to eventually explore!
