### ISSUE TITLE
can't read slack api docs

### ISSUE THREAD

**Issue by jahlbornG** [sethcottle/tabcloser#6]
tab closer will close any slack api docs, e.g. "https://api.slack.com/events/message/bot_message".

**Comment by sethcottle** [comment]
Thanks so much for for catching this and so sorry you encountered it! I had just done some work on the regex for Slack a few weeks ago to avoid some other issues with it, this was not one of them. I just published a commit to fix this:

https://github.com/sethcottle/tabcloser/commit/5c3e0c4dad6ef7d5a7f18f6bd666fc722b9f25fa

`^https?://(?!(app\\.slack\\.com|slack\\.com|api\\.slack\\.com|.*\\/(customize|account|apps)(\\/|$)|.*\\/home(\\/|$)))[a-z0-9-]+\\.slack\\.com/.*$`

With this update to the regex, `api\\.slack\\.com` is added right after `slack\\.com` within the negative lookahead assertion `(?!(...))`. This ensures that any URL that starts with `https://api.slack.com` will not be matched by the regular expression, and won't be closed by TabCloser! I'll get this bundled as a manual release here on GitHuib and submit the update to the Chrome Web Store and the Edge Add On store!

In the meantime, if you want to wait for the update, just disabled Slack in the TabCloser menu. 

![d33a230f06e72e16b6a1bd891bc385ab](https://github.com/sethcottle/tabcloser/assets/1301949/6a24b97d-d64e-4a65-acbf-e0a17310d145)

**Comment by sethcottle** [comment]
Release was published on GitHub for this if you'd like to manually update the extension.

https://github.com/sethcottle/tabcloser/releases/tag/v2.7.6

**Comment by sethcottle** [comment]
v2.7.6 pending on the [Chrome Web Store](https://chromewebstore.google.com/) and [Edge Add-ons](https://microsoftedge.microsoft.com/addons/Microsoft-Edge-Extensions-Home) store. Thanks again!


![Pending](https://github.com/sethcottle/tabcloser/assets/1301949/ab5fe10d-344c-4cad-8994-febac4631921)
